/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyCenterIndexRouteImport } from './routes/privacy-center/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PrivacyCenterVoucherRouteImport } from './routes/privacy-center/voucher'
import { Route as PrivacyCenterSureMarkRouteImport } from './routes/privacy-center/sure-mark'
import { Route as PrivacyCenterSelfCheckRouteImport } from './routes/privacy-center/self-check'
import { Route as PrivacyCenterLawRouteImport } from './routes/privacy-center/law'
import { Route as PrivacyCenterAssociationApplyRouteImport } from './routes/privacy-center/association-apply'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyCenterIndexRoute = PrivacyCenterIndexRouteImport.update({
  id: '/privacy-center/',
  path: '/privacy-center/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyCenterVoucherRoute = PrivacyCenterVoucherRouteImport.update({
  id: '/privacy-center/voucher',
  path: '/privacy-center/voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyCenterSureMarkRoute = PrivacyCenterSureMarkRouteImport.update({
  id: '/privacy-center/sure-mark',
  path: '/privacy-center/sure-mark',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyCenterSelfCheckRoute = PrivacyCenterSelfCheckRouteImport.update({
  id: '/privacy-center/self-check',
  path: '/privacy-center/self-check',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyCenterLawRoute = PrivacyCenterLawRouteImport.update({
  id: '/privacy-center/law',
  path: '/privacy-center/law',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyCenterAssociationApplyRoute =
  PrivacyCenterAssociationApplyRouteImport.update({
    id: '/privacy-center/association-apply',
    path: '/privacy-center/association-apply',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/history': typeof HistoryRoute
  '/privacy-center/association-apply': typeof PrivacyCenterAssociationApplyRoute
  '/privacy-center/law': typeof PrivacyCenterLawRoute
  '/privacy-center/self-check': typeof PrivacyCenterSelfCheckRoute
  '/privacy-center/sure-mark': typeof PrivacyCenterSureMarkRoute
  '/privacy-center/voucher': typeof PrivacyCenterVoucherRoute
  '/admin/': typeof AdminIndexRoute
  '/privacy-center/': typeof PrivacyCenterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/history': typeof HistoryRoute
  '/privacy-center/association-apply': typeof PrivacyCenterAssociationApplyRoute
  '/privacy-center/law': typeof PrivacyCenterLawRoute
  '/privacy-center/self-check': typeof PrivacyCenterSelfCheckRoute
  '/privacy-center/sure-mark': typeof PrivacyCenterSureMarkRoute
  '/privacy-center/voucher': typeof PrivacyCenterVoucherRoute
  '/admin': typeof AdminIndexRoute
  '/privacy-center': typeof PrivacyCenterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/history': typeof HistoryRoute
  '/privacy-center/association-apply': typeof PrivacyCenterAssociationApplyRoute
  '/privacy-center/law': typeof PrivacyCenterLawRoute
  '/privacy-center/self-check': typeof PrivacyCenterSelfCheckRoute
  '/privacy-center/sure-mark': typeof PrivacyCenterSureMarkRoute
  '/privacy-center/voucher': typeof PrivacyCenterVoucherRoute
  '/admin/': typeof AdminIndexRoute
  '/privacy-center/': typeof PrivacyCenterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/business'
    | '/contact'
    | '/history'
    | '/privacy-center/association-apply'
    | '/privacy-center/law'
    | '/privacy-center/self-check'
    | '/privacy-center/sure-mark'
    | '/privacy-center/voucher'
    | '/admin/'
    | '/privacy-center/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/business'
    | '/contact'
    | '/history'
    | '/privacy-center/association-apply'
    | '/privacy-center/law'
    | '/privacy-center/self-check'
    | '/privacy-center/sure-mark'
    | '/privacy-center/voucher'
    | '/admin'
    | '/privacy-center'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/business'
    | '/contact'
    | '/history'
    | '/privacy-center/association-apply'
    | '/privacy-center/law'
    | '/privacy-center/self-check'
    | '/privacy-center/sure-mark'
    | '/privacy-center/voucher'
    | '/admin/'
    | '/privacy-center/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  BusinessRoute: typeof BusinessRoute
  ContactRoute: typeof ContactRoute
  HistoryRoute: typeof HistoryRoute
  PrivacyCenterAssociationApplyRoute: typeof PrivacyCenterAssociationApplyRoute
  PrivacyCenterLawRoute: typeof PrivacyCenterLawRoute
  PrivacyCenterSelfCheckRoute: typeof PrivacyCenterSelfCheckRoute
  PrivacyCenterSureMarkRoute: typeof PrivacyCenterSureMarkRoute
  PrivacyCenterVoucherRoute: typeof PrivacyCenterVoucherRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PrivacyCenterIndexRoute: typeof PrivacyCenterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-center/': {
      id: '/privacy-center/'
      path: '/privacy-center'
      fullPath: '/privacy-center/'
      preLoaderRoute: typeof PrivacyCenterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-center/voucher': {
      id: '/privacy-center/voucher'
      path: '/privacy-center/voucher'
      fullPath: '/privacy-center/voucher'
      preLoaderRoute: typeof PrivacyCenterVoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-center/sure-mark': {
      id: '/privacy-center/sure-mark'
      path: '/privacy-center/sure-mark'
      fullPath: '/privacy-center/sure-mark'
      preLoaderRoute: typeof PrivacyCenterSureMarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-center/self-check': {
      id: '/privacy-center/self-check'
      path: '/privacy-center/self-check'
      fullPath: '/privacy-center/self-check'
      preLoaderRoute: typeof PrivacyCenterSelfCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-center/law': {
      id: '/privacy-center/law'
      path: '/privacy-center/law'
      fullPath: '/privacy-center/law'
      preLoaderRoute: typeof PrivacyCenterLawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-center/association-apply': {
      id: '/privacy-center/association-apply'
      path: '/privacy-center/association-apply'
      fullPath: '/privacy-center/association-apply'
      preLoaderRoute: typeof PrivacyCenterAssociationApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  BusinessRoute: BusinessRoute,
  ContactRoute: ContactRoute,
  HistoryRoute: HistoryRoute,
  PrivacyCenterAssociationApplyRoute: PrivacyCenterAssociationApplyRoute,
  PrivacyCenterLawRoute: PrivacyCenterLawRoute,
  PrivacyCenterSelfCheckRoute: PrivacyCenterSelfCheckRoute,
  PrivacyCenterSureMarkRoute: PrivacyCenterSureMarkRoute,
  PrivacyCenterVoucherRoute: PrivacyCenterVoucherRoute,
  AdminIndexRoute: AdminIndexRoute,
  PrivacyCenterIndexRoute: PrivacyCenterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
